version: 2

sources:
  - name: staging
    database: earthquake-data-467123
    schema: earthquake_stg_data
    tables:
      - name: stg_earthquake_data_historical
      - name: stg_earthquake_data_monthly
  
models:
  - name: stg_earthquake
    description: >
      Earthquake data extracted from USGS API.
    columns: 
      - name: place
        description: Geographic region determined to be closest to the event
      - name: earthquake_datetime
        description: Time when the event occurred
      - name: magnitude
        description: Magnitude recorded for the event
      - name: latitude
        description: Decimal degrees latitude of recorded epicenter
      - name: longitude
        description: Decimal degrees longitude of recorded epicenter
      - name: depth
        description: Depth where the event begins to rupture
      - name: country
        description: Country the epicenter is recorded
      - name: region
        description: Region the epicenter is located
      - name: alert
        description: >
          Alert level based on PAGER earthquake impact scale
            Green = Little or no impact expected
            Yellow = Regional impact and response. Thresholds for 
                yellow alerts are typically around 1 million USD in losses and 1 fatality, according to the USGS.
            Orange = National-scale impact and response. Thresholds for orange alerts are typically around 100 
                million USD in losses and 100 fatalities, according to the USGS.
            Red = International impact and response. Thresholds for red alerts are typically around 1 billion 
                USD in losses and 1000 fatalities, according to the USGS.
      - name: tsunami
        description: Indication if event was recorded in NOAA Tsunami website for tsunami information. Usually large events.
      - name: type
        description: Type of seismic event
      
  - name: fact_earthquake_data
    columns:
      - name: severity
        description: Classification of earthquake strength based on magnitude
      - name: event_year
        description: The year the event was recorded
      - name: event_decade
        description: The decade the event was recorded